version: "3"
services:
  gitlab:
    container_name: gitlab
    image: sameersbn/gitlab:10.6.4
    ports:
      - "10022:22"
    links: 
      - gitlab-redis:redisio
      - gitlab-postgresql:postgresql
    environment:
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=10022
      - GITLAB_HTTPS=true
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string
      - LDAP_ENABLED=true
      - LDAP_HOST=ldap
      - LDAP_UID=cn
      - LDAP_BIND_DN=cn=admin,dc=xjbw,dc=com
      - LDAP_PASS=xjbwinfo
      - LDAP_BASE=ou=people,dc=xjbw,dc=com
      - LDAP_USER_FILTER=(&(objectClass=inetOrgPerson)(cn=%n))
      - VIRTUAL_HOST=gitlab.info.baiwangjinfu.com
      - LETSENCRYPT_HOST=gitlab.info.baiwangjinfu.com
      - LETSENCRYPT_EMAIL=alex_wuya@163.com
      - VIRTUAL_PORT=80
    volumes:
      - ~/data/gitlab/gitlab:/home/git/data
    depends_on:
      - gitlab-redis
      - gitlab-postgresql
    restart: always
 
  gitlab-redis:
    container_name: gitlab-redis 
    image: sameersbn/redis
    volumes:
      - ~/data/gitlab/redis:/var/lib/redis
    restart: always
 
  gitlab-postgresql:
    container_name: gitlab-postgresql
    image: sameersbn/postgresql:9.6-2
    environment:
        - DB_NAME=gitlabhq_production
        - DB_USER=gitlab
        - DB_PASS=password
        - DB_EXTENSION=pg_trgm
    volumes:
      - ~/data/gitlab/postgresql:/var/lib/postgresql
    restart: always

