version: "3"
services:
  gitlab:
    container_name: gitlab
    image: sameersbn/gitlab
    ports:
      - "10022:22"
    links: 
      - gitlab-redis:redisio
      - gitlab-postgresql:postgresql
    environment:
      - DEBUG=false
      - DB_ADAPTER=postgresql
      - DB_HOST=gitlab-postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379

      - TZ=Asia/Shanghai
      - GITLAB_TIMEZONE=Asia/Shanghai
      - GITLAB_HOST=git.bwjf.cn
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=10022
      - GITLAB_HTTPS=true
      - SSL_SELF_SIGNED=false
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string
      - LDAP_ENABLED=true
      - LDAP_HOST=ldap
      - LDAP_UID=cn
      - LDAP_BIND_DN=cn=admin,dc=bwjf,dc=cn
      - LDAP_PASS=Xjbw0601
      - LDAP_BASE=ou=people,dc=bwjf,dc=cn
      - LDAP_USER_FILTER=(&(objectClass=inetOrgPerson)(cn=*))
      - VIRTUAL_HOST=git.bwjf.cn
      - VIRTUAL_PORT=80
    volumes:
      - ~/data/gitlab/gitlab:/home/git/data
    depends_on:
      - gitlab-redis
      - gitlab-postgresql
    restart: always
 
  gitlab-redis:
    container_name: gitlab-redis 
    image: sameersbn/redis
    volumes:
      - ~/data/gitlab/redis:/var/lib/redis
    restart: always
 
  gitlab-postgresql:
    container_name: gitlab-postgresql
    image: sameersbn/postgresql
    environment:
        - DB_NAME=gitlabhq_production
        - DB_USER=gitlab
        - DB_PASS=password
        - DB_EXTENSION=pg_trgm
    volumes:
      - ~/data/gitlab/postgresql:/var/lib/postgresql
    restart: always

